@host = http://localhost:8000

### Preflight test for /watchlist/
OPTIONS {{host}}/watchlist/
Origin: http://localhost:5173
Access-Control-Request-Method: POST
Access-Control-Request-Headers: Content-Type, X-User-Id
###
POST  {{host}}/industries/
Content-Type: application/json

{
	"sectors": ["basic-materials"]
}

###
GET {{host}}/getStockInfo/?max=5&offset=0
###
GET {{host}}/searchStocks/a/1
###
GET  {{host}}/watchlist/
Content-Type: application/json

{
	"symbol": "AAPL"
}
###
Get {{host}}/stock/aapl
###
POST {{host}}/screeners/database/
Content-Type: application/json

[
]

###
DELETE {{host}}/watchlist/remove/
Content-Type: application/json

{
	"symbol": "AAPL"
}

###
POST {{host}}/watchlist/add/
Content-Type: application/json

{
	"symbol": "BRX"
}

###
GET {{host}}/watchlist/search/?query=Apple

###
GET {{host}}/watchlist/sorted/

###
GET {{host}}/watchlist/sorted/?reverse=true

###
POST {{host}}/stocks/
Content-Type: application/json

{
	"symbol": "AAPL",
	"company_name": "Apple Inc."
}

###
GET {{host}}/stocks/

### 
GET {{host}}/screeners/custom/1
"X-User-Id": 

###
GET {{host}}/fear-greed/csv/
Accept: application/json
### Get all user stock potentials
GET {{host}}/api/user-stock-potentials/
X-User-Id: test-api-key-12345

### Create a new user stock potential
POST {{host}}/api/user-stock-potentials/
Content-Type: application/json
X-User-Id: test-api-key-12345

{
	"stock_symbol": "AAPL",
	"purchase_date": "2026-01-15",
	"quantity": "100.0000",
	"purchase_price": "150.50"
}

###

### Get EPS for a specific stock
GET {{host}}/stock/AAPL/eps/
Accept: application/json

