# Generated by Django 4.2.23 on 2025-09-27 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='hello.account')),
            ],
            options={
                'db_table': 'watchlist',
            },
        ),
        migrations.CreateModel(
            name='WatchlistStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(db_column='stock_symbol', on_delete=django.db.models.deletion.CASCADE, to='hello.stock')),
                ('watchlist', models.ForeignKey(db_column='watchlist_id', on_delete=django.db.models.deletion.CASCADE, to='hello.watchlist')),
            ],
            options={
                'db_table': 'watchlist_stock',
            },
        ),
    ]
