# Generated by Django 4.2.23 on 2025-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(related_name='watchlists', through='hello.WatchlistStock', to='hello.stock'),
        ),
    ]
