@host = http://localhost:8000
###
GET {{host}}/getStocks/AAPL

###
GET {{host}}/getStockInfo/?max=5&offset=0
###
GET {{host}}/searchStocks/a/1
###
GET  {{host}}/watchlist/
Content-Type: application/json

{
	"symbol": "AAPL"
}
###
Get {{host}}/stock/aapl
###
GET {{host}}/watchlist/

###
DELETE {{host}}/watchlist/remove/
Content-Type: application/json

{
	"symbol": "AAPL"
}

###
POST {{host}}/watchlist/add/
Content-Type: application/json

{
	"symbol": "BRX"
}

###
GET {{host}}/watchlist/search/?query=Apple

###
GET {{host}}/watchlist/sorted/

###
GET {{host}}/watchlist/sorted/?reverse=true

###
POST {{host}}/stocks/
Content-Type: application/json

{
	"symbol": "AAPL",
	"company_name": "Apple Inc."
}

###
GET {{host}}/stocks/

### 
GET {{host}}/screeners/custom/1
"X-User-Id": 