# Generated by Django 5.2.6 on 2025-11-05 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('keycloak_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoricalFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categorical_filter',
            },
        ),
        migrations.CreateModel(
            name='NumericFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'numeric_filter',
            },
        ),
        migrations.CreateModel(
            name='Screener',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'screener',
            },
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='CustomCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=20)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Incrementum.account')),
            ],
            options={
                'db_table': 'custom_collection',
            },
        ),
        migrations.CreateModel(
            name='CustomScreener',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screener_name', models.CharField(default='Untitled Screener', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.account')),
            ],
            options={
                'db_table': 'custom_screener',
            },
        ),
        migrations.CreateModel(
            name='CustomCollectionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.customcollection')),
                ('stock', models.ForeignKey(db_column='stock_symbol', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.stockmodel')),
            ],
            options={
                'db_table': 'custom_collection_stock',
                'managed': True,
                'unique_together': {('collection', 'stock')},
            },
        ),
        migrations.AddField(
            model_name='customcollection',
            name='stocks',
            field=models.ManyToManyField(related_name='custom_collections', through='Incrementum.CustomCollectionStock', to='Incrementum.stockmodel'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.account')),
            ],
            options={
                'db_table': 'watchlist',
            },
        ),
        migrations.CreateModel(
            name='WatchlistStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(db_column='stock_symbol', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.stockmodel')),
                ('watchlist', models.ForeignKey(db_column='watchlist_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.watchlist')),
            ],
            options={
                'db_table': 'watchlist_stock',
                'managed': True,
                'unique_together': {('watchlist', 'stock')},
            },
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(related_name='watchlists', through='Incrementum.WatchlistStock', to='Incrementum.stockmodel'),
        ),
        migrations.CreateModel(
            name='CustomScreenerCategorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_value', models.CharField(blank=True, max_length=20, null=True)),
                ('categorical_filter', models.ForeignKey(db_column='categorical_filter_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.categoricalfilter')),
                ('custom_screener', models.ForeignKey(db_column='custom_screener_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.customscreener')),
            ],
            options={
                'db_table': 'custom_screener_categorical',
                'unique_together': {('custom_screener', 'categorical_filter')},
            },
        ),
        migrations.CreateModel(
            name='CustomScreenerNumeric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.IntegerField(blank=True, null=True)),
                ('custom_screener', models.ForeignKey(db_column='custom_screener_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.customscreener')),
                ('numeric_filter', models.ForeignKey(db_column='numeric_filter_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.numericfilter')),
            ],
            options={
                'db_table': 'custom_screener_numeric',
                'unique_together': {('custom_screener', 'numeric_filter')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistCustomScreener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_screener', models.ForeignKey(db_column='custom_screener_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.customscreener')),
                ('watchlist', models.ForeignKey(db_column='watchlist_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.watchlist')),
            ],
            options={
                'db_table': 'watchlist_custom_screener',
                'unique_together': {('watchlist', 'custom_screener')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistScreener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screener', models.ForeignKey(db_column='screener_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.screener')),
                ('watchlist', models.ForeignKey(db_column='watchlist_id', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.watchlist')),
            ],
            options={
                'db_table': 'watchlist_screener',
                'unique_together': {('watchlist', 'screener')},
            },
        ),
    ]
