# Generated by Django 4.2.25 on 2025-11-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0002_add_c_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcollectionstock',
            options={'managed': False},
        ),
    ]
