# Generated by Django 4.2.25 on 2025-11-05 22:14
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0003_alter_customcollectionstock_options'),
    ]

    operations = [
        # First add the field as nullable
        migrations.AddField(
            model_name='customcollection',
            name='date_created',
            field=models.DateField(db_column='date_created', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
