# Generated by Django 4.2.25 on 2025-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0003_alter_customcollectionstock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcollection',
            name='date_created',
            field=models.DateField(db_column='date_created', default=None),
            preserve_default=False,
        ),
    ]
