# Generated by Django 4.2.25 on 2025-11-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0004_customcollection_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcollection',
            name='date_created',
            field=models.DateField(auto_now_add=True, db_column='date_created'),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='symbol',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
