# Generated by Django 5.2.6 on 2025-11-25 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0005_increase_symbol_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('day_and_time', models.DateTimeField()),
                ('open_price', models.IntegerField()),
                ('close_price', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_history',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
