# Generated by Django 5.1.3 on 2026-01-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0008_create_stock_history_and_blacklist_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistcustomscreener',
            name='custom_screener',
        ),
        migrations.RemoveField(
            model_name='watchlistcustomscreener',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='watchlistscreener',
            name='screener',
        ),
        migrations.RemoveField(
            model_name='watchlistscreener',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='watchliststock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='watchliststock',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='account',
        ),
        migrations.DeleteModel(
            name='WatchlistCustomScreener',
        ),
        migrations.DeleteModel(
            name='WatchlistScreener',
        ),
        migrations.DeleteModel(
            name='WatchlistStock',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
