# Generated by Django 5.2.6 on 2026-01-15 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0008_create_stock_history_and_blacklist_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('time_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'blacklist',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
