# Generated by Django 5.1.3 on 2026-01-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0009_blacklist_alter_stockmodel_updated_at'),
    ]

    operations = [
        # Delete models directly - SQLite handles foreign keys automatically
        migrations.DeleteModel(
            name='WatchlistCustomScreener',
        ),
        migrations.DeleteModel(
            name='WatchlistScreener',
        ),
        migrations.DeleteModel(
            name='WatchlistStock',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
