# Generated by Django 5.2.6 on 2026-01-23 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incrementum', '0012_user_stock_potential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstockpotential',
            name='stock_symbol',
            field=models.ForeignKey(db_column='stock_symbol', on_delete=django.db.models.deletion.CASCADE, to='Incrementum.stockmodel'),
        ),
    ]
