name: Python Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -f Incrementum.api/test.Dockerfile -t incrementum-test ./Incrementum.api

      - name: Run tests
        run: docker run --rm incrementum-test
